language: generic 

# build scripts
sudo: required
services: 
  - docker

# pre-work to run test of the app
before_install:
  - docker build -t honglin/docker-react -f Dockerfile.dev .

# actual commands to run
script:
  - docker run -e CI=true honglin/docker-react npm run test

# deploy scripts only when master branch gets merged
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"